### ISSUE TITLE
MacOs app wont launch

### ISSUE THREAD

**Issue by shteffen** [glegrain/STM32-with-macOS#2]
After going through the process of installing Java 8 and installing STM32CubeProgrammer (v. 2.1.0), the app still won't launch. It just immediately closes after startup. In terminal, trying to open it returns the error: "LSOpenURLsWithRole() failed with error -10810 for the file...".

**Comment by EdwardEisenhauer** [comment]
I have a similar problem, in my case it throws:

```
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:473)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:372)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:945)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:973)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:198)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: javafx.fxml.LoadException: 
file:/Applications/STMicroelectronics/STM32Cube/STM32CubeProgrammer/STM32CubeProgrammer.app/Contents/MacOs/bin/STM32CubeProgrammer!/fxml/MainWindow.fxml

	at javafx.fxml/javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2625)
	at javafx.fxml/javafx.fxml.FXMLLoader.importClass(FXMLLoader.java:2863)
	at javafx.fxml/javafx.fxml.FXMLLoader.processImport(FXMLLoader.java:2707)
	at javafx.fxml/javafx.fxml.FXMLLoader.processProcessingInstruction(FXMLLoader.java:2676)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2542)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3253)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3210)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3179)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3152)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3129)
	at javafx.fxml/javafx.fxml.FXMLLoader.load(FXMLLoader.java:3122)
	at com.st.app.Main.start(Main.java:38)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:919)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(PlatformImpl.java:449)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.scene.control.skin.ContextMenuContent$MenuBox
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadTypeForPackage(FXMLLoader.java:2931)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadType(FXMLLoader.java:2920)
	at javafx.fxml/javafx.fxml.FXMLLoader.importClass(FXMLLoader.java:2861)
	... 17 more
Exception running application com.st.app.Main
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

```

**Comment by donn** [comment]
On Catalina, the programmer doesn't work anyway. I recommend using st-flash instead.

**Comment by glegrain** [comment]
I managed to install STM32CubeProgrammer v2.4.0 on macOS 10.15.3 by:
1. Removing any existing java installation. If you `type java -version` in your terminal, there should not be any java install present.
2. Installing [Java SE Development Kit 8](https://www.oracle.com/java/technologies/javase-jdk8-downloads.html). (I used 1.8.0_241)
3. Installing STM32CubeProgrammer. JavaVersion should be 1.8.xx.
```
$ sudo java -jar SetupSTM32CubeProgrammer-2.2.1.exe
Command line arguments: 
====================
Installation started
Framework: 1.6.0_65-b14-468 (Apple Inc.)
Platform: mac_osx,version=10.15.3,arch=x86,symbolicName=null,javaVersion=1.8.0_241
Installation finished
```

https://community.st.com/s/question/0D50X0000BmnqrBSQQ/how-to-run-stm32cubeprogrammer-on-macos-catalina-10151-19b88

**Comment by IoTeacher** [comment]
Please UPDATE the README.md on the line...
_Homebrew update URL:_
`$ brew install homebrew/cask/gcc-arm-embedded`


![Screen Shot 2020-03-16 at 21 06 01](https://user-images.githubusercontent.com/2523851/76820933-bfab8d80-67c9-11ea-8da0-dc57c267db07.png)

**Comment by dlwalter** [comment]
Attempting with SetupSTM32CubeProgrammer-2.5.0 and the app won't launch on macOS.
